version: '3.7'

services:
  lambda:
    container_name: lambda
    image: lambci/lambda:python3.7
    command: app.lambda_handler
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - DOCKER_LAMBDA_DEBUG=1
      - TZ=America/New_york
    volumes:
      - ./reward:/var/task:ro,delegated
      - ./lib:/opt:ro,delegated
  api:
    container_name: api
    image: elthrasher/http-lambda-invoker
    environment:
      - LAMBDA_ENDPOINT=http://lambda:9001
      - LAMBDA_NAME=reward
      - PORT=8080
    ports:
      - '18080:8080'
